version: '3.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: microserviceproto_zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: microserviceproto_kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "hostname -I | awk -F' ' '{print $$1}'"
    depends_on:
      - zookeeper
