spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        streams-in:
          destination: messages
          contentType: application/json
        dead-out:
          destination: dead-out
          contentType: application/json
