spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        streams-out:
          destination: messages
          contentType: application/json
