spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          autoAddPartitions: true
      bindings:
        streams-out:
          destination: messages
          contentType: application/json
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
