spring:
  cloud:
    stream:
      bindings:
        streams-mirror:
          contentType: application/json
          destination: messages-mirror
        streams-count:
          contentType: application/json
          destination: messages-count
        streams-in:
          destination: messages
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          bindings:
            streams-in:
              consumer:
                application-id: processor
          binder:
            configuration:
              commit:
                interval:
                  ms: 1000
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
